[package]
name = "lang"
version = "0.1.0"
edition = "2021"
build = "codegen/main.rs"

[dependencies]
annotate-snippets = "0.11.4"
chumsky = { git = "https://github.com/zesterer/chumsky", rev = "6aa77b8a7687a0d1a02b2858cca713ef0433bfab", version = "1.0.0-alpha.7", features = ["extension"] }
colored = "2.1.0"
cstree = "0.12.2"
logos = "0.14.2"

[dev-dependencies]
ctrlc = "3.4.5"
serde_json = "1.0.128"
ui_test = "0.27.1"
xshell = "0.2.6"
cargo_metadata = "0.18.1"

[[test]]
name = "ui_test"
harness = false

[build-dependencies]
prettyplease = "0.2.24"
proc-macro2 = "1.0.88"
quote = "1.0.37"
syn = "2.0.82"
ungrammar = "1.16.1"
