name: Deploy to gh pages

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: install dx
      run: cargo install dioxus-cli@0.5.1
    - name: install dependencies
      run: sudo apt update && sudo apt -yq install libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev
    - name: build for wasm
      run: cd app && dx build --release --platform web
    - name: GitHub Pages
      if: github.event_name != 'pull_request'
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        # Build directory to deploy
        build_dir: app/dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
