name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run lang tests
      run: cargo test --verbose --manifest-path lang/Cargo.toml
    - name: Build app
      run: cargo check --verbose --manifest-path app/Cargo.toml
